export let allProducts = [
  {
    id: 1,
    img: "./img/Cross.svg",
    title: `Вариативный замок Golden Soft  для отеля`,
    discountPrice: 7000,
    realP: 8000,
    categorios: ["popular", "summer"],
    reyting: "(12) отзывов",
    hasBasket: false,
  },
  {
    id: 2,
    img: "./img/Cross.svg",
    title: "Вариативный замок Golden Soft для отеля",
    discountPrice: 7000,
    realP: 8000,
    categorios: ["popular", "summer"],
    reyting: "(12) отзывов",
    hasBasket: false,
  },
  {
    id: 3,
    img: "./img/Cross.svg",
    title: "Вариативный замок Golden Soft для отеля",
    discountPrice: 7000,
    realP: 8000,
    categorios: ["popular", "summer"],
    reyting: "(12) отзывов",
    hasBasket: false,
  },
  {
    id: 4,
    img: "./img/Cross.svg",
    title: "Вариативный замок Golden Soft для отеля",
    discountPrice: 7000,
    realP: 8000,
    categorios: ["popular", "summer"],
    reyting: "(12) отзывов",
    hasBasket: false,
  },
  {
    id: 5,
    img: "./img/Cross.svg",
    title: "Вариативный замок Golden Soft для отеля",
    discountPrice: 7000,
    realP: 8000,
    categorios: ["popular", "summer"],
    reyting: "(12) отзывов",
    hasBasket: false,
  },
  {
    id: 6,
    img: "./img/Cross.svg",
    title: "Вариативный замок Golden Soft для отеля",
    discountPrice: 7000,
    realP: 8000,
    categorios: ["popular", "summer"],
    reyting: "(12) отзывов",
    hasBasket: false,
  },
  {
    id: 7,
    img: "./img/Cross.svg",
    title: "Вариативный замок Golden Soft для отеля",
    discountPrice: 7000,
    realP: 8000,
    categorios: ["popular", "summer"],
    reyting: "(12) отзывов",
    hasBasket: false,
  },
  {
    id: 8,
    img: "./img/Cross.svg",
    title: "Вариативный замок Golden Soft для отеля",
    discountPrice: 7000,
    realP: 8000,
    categorios: ["popular", "summer"],
    reyting: "(12) отзывов",
    hasBasket: false,
  },
  {
    id: 9,
    img: "./img/Cross.svg",
    title: "Вариативный замок Golden Soft для отеля",
    discountPrice: 7000,
    realP: 8000,
    categorios: ["popular", "summer"],
    reyting: "(12) отзывов",
    hasBasket: false,
  },
];
