export let allProducts = localStorage.getItem("product")
  ? JSON.parse(localStorage.getItem("product"))
  : [
      {
        id: 1,
        img: "./img/Rectangle 19 (4).svg",
        reyting: "(15) отзывов",
        title: `Вариативный замок Golden Soft  для отеля`,
        discountPrice: 36000,
        realP: 8000,
        allCategories: ["popular", "Популярности"],
        hasBasket: false,
      },
      {
        id: 2,
        img: "./img/Rectangle 19 (4).svg",
        title: "Вариативный замок Golden Soft для отеля",
        discountPrice: 26000,
        realP: 7000,
        allCategories: ["popular", "summer"],
        reyting: "(25) отзывов",
        hasBasket: false,
      },
      {
        id: 3,
        img: "./img/Rectangle 19 (4).svg",
        title: "Вариативный замок Golden Soft для отеля",
        discountPrice: 10000,
        realP: 8000,
        allCategories: ["popular", "summer"],
        reyting: "(36) отзывов",
        hasBasket: false,
      },
      {
        id: 4,
        img: "./img/Rectangle 19 (4).svg",
        title: "Вариативный замок Golden Soft для отеля",
        discountPrice: 19000,
        realP: 8000,
        allCategories: ["popular"],
        reyting: "(28) отзывов",
        hasBasket: false,
      },
      {
        id: 5,
        img: "./img/Rectangle 19 (4).svg",
        title: "Вариативный замок Golden Soft для отеля",
        discountPrice: 27000,
        realP: 8000,
        allCategories: ["popular", "summer"],
        reyting: "(34) отзывов",
        hasBasket: false,
      },
      {
        id: 6,
        img: "./img/Rectangle 19 (4).svg",
        title: "Вариативный замок Golden Soft для отеля",
        discountPrice: 15000,
        realP: 8000,
        allCategories: ["popular", "summer"],
        reyting: "(65) отзывов",
        hasBasket: false,
      },
      {
        id: 7,
        img: "./img/Rectangle 19 (4).svg",
        title: "Вариативный замок Golden Soft для отеля",
        discountPrice: 7000,
        realP: 8000,
        allCategories: ["popular"],
        reyting: "(19) отзывов",
        hasBasket: false,
      },
      {
        id: 8,
        img: "./img/Rectangle 19 (4).svg",
        title: "Вариативный замок Golden Soft для отеля",
        discountPrice: 5000,
        realP: 8000,
        allCategories: ["popular", "summer"],
        reyting: "(18) отзывов",
        hasBasket: false,
      },
      {
        id: 9,
        img: "./img/Rectangle 19 (4).svg",
        title: "Вариативный замок Golden Soft для отеля",
        discountPrice: 7000,
        realP: 8000,
        allCategories: ["popular", "summer", "test"],
        reyting: "(36) отзывов",
        hasBasket: false,
      },
    ];
