export let allProducts = localStorage.getItem("product")
  ? JSON.parse(localStorage.getItem("product"))
  : [
      {
        id: 1,
        img: "./img/Rectangle 19 (4).svg",
        reyting: "(15) отзывов",
        title: `Вариативный замок Golden Soft  для отеля`,
        discountPrice: "5000",
        realP: "8 000₽",
        allCategories: ["popular", "Популярности"],
        hasBasket: false,
      },
      {
        id: 2,
        img: "./img/Rectangle 19 (4).svg",
        title: "Вариативный замок Golden Soft для отеля",
        discountPrice: 7000,
        realP: 7000,
        allCategories: ["popular", "summer"],
        reyting: "(12) отзывов",
        hasBasket: false,
      },
      {
        id: 3,
        img: "./img/Rectangle 19 (4).svg",
        title: "Вариативный замок Golden Soft для отеля",
        discountPrice: "10 000",
        realP: 8000,
        allCategories: ["popular", "summer"],
        reyting: "(12) отзывов",
        hasBasket: false,
      },
      {
        id: 4,
        img: "./img/Rectangle 19 (4).svg",
        title: "Вариативный замок Golden Soft для отеля",
        discountPrice: 7000,
        realP: 8000,
        categorios: ["popular"],
        reyting: "(12) отзывов",
        hasBasket: false,
      },
      {
        id: 5,
        img: "./img/Rectangle 19 (4).svg",
        title: "Вариативный замок Golden Soft для отеля",
        discountPrice: 7000,
        realP: 8000,
        allCategories: ["popular", "summer"],
        reyting: "(12) отзывов",
        hasBasket: false,
      },
      {
        id: 6,
        img: "./img/Rectangle 19 (4).svg",
        title: "Вариативный замок Golden Soft для отеля",
        discountPrice: 7000,
        realP: 8000,
        allCategories: ["popular", "summer"],
        reyting: "(12) отзывов",
        hasBasket: false,
      },
      {
        id: 7,
        img: "./img/Rectangle 19 (4).svg",
        title: "Вариативный замок Golden Soft для отеля",
        discountPrice: 7000,
        realP: 8000,
        allCategories: ["popular"],
        reyting: "(12) отзывов",
        hasBasket: false,
      },
      {
        id: 8,
        img: "./img/Rectangle 19 (4).svg",
        title: "Вариативный замок Golden Soft для отеля",
        discountPrice: 7000,
        realP: 8000,
        allCategories: ["popular", "summer"],
        reyting: "(12) отзывов",
        hasBasket: false,
      },
      {
        id: 9,
        img: "./img/Rectangle 19 (4).svg",
        title: "Вариативный замок Golden Soft для отеля",
        discountPrice: 7000,
        realP: 8000,
        allCategories: ["popular", "summer", "test"],
        reyting: "(12) отзывов",
        hasBasket: false,
      },
    ];
